@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZW1iZXJJZCI6MSwibmFtZSI6Iu2ajOybkCDthYzsiqTtirgiLCJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJyb2xlIjoiVXNlciIsImlhdCI6MTcwMjc0OTE0OSwiZXhwIjoxNzAyNzUyNzQ5fQ.1mk3BfaS1qHOCzXQqvpLaiYkzX3ROhgda2V32FHval0

### 펫시터 회원가입 하기
POST   http://localhost:3010/api/sign-up/pet-sitters
Content-Type: application/json

{
  "email" : "test3@test.com",
  "name" : "테스트2",
  "age" : 19,
  "selfIntro" : "반갑습니다.",
  "availablePet" : "Dog",
  "availableAddress" : "서울",
  "certificate" : "없음",
  "score" : "",
  "imagePath" : "123123123",
  "password" : "123456",
  "confirmPassword" : "123456"
}


### 펫시터 로그인 하기
POST  http://localhost:3010/api/sign-in/pet-sitters
Content-Type: application/json

{
  "email" : "test3@test.com",
  "password" : "123456"
}





### 일반회원 가입 하기
POST   http://localhost:3010/api/sign-up/users
Content-Type: application/json

{
  "email" : "test@test.com",
  "name" : "1회원 테스트",
  "age" : 19,
  "address" : "서울",
  "imagePath" : "123123123",
  "password" : "123456",
  "confirmPassword" : "123456"
}

#


### 일반회원 로그인 하기
POST  http://localhost:3010/api/sign-in/users
Content-Type: application/json

{
  "email" : "test@test.com",
  "password" : "123456"
}




### 내 정보 조회?
GET http://localhost:3010/api/my-profile/users
authorization: Bearer {{token}}