@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZW1iZXJJZCI6MywibmFtZSI6IjHtmozsm5Ag7YWM7Iqk7Yq4IiwiZW1haWwiOiIzdGVzdEB0ZXN0LmNvbSIsInJvbGUiOiJVc2VyIiwiaWF0IjoxNzAyNjEwODM3LCJleHAiOjE3MDI2MTQ0Mzd9.bzDSdw2uJ_rddl4vVc7hUEu6SB2ReTaH5HsU7Jl2gac

###테스트 데이터 넣기
POST http://localhost:3010/api/pet-sitters/petSitter/post 
Content-Type: application/json

{
  "petSitterName": "공공이",
	"age": 22,
	"selfIntro": "안녕하세요 저는 공공이가 좋아요",
	"availablePet": "Dog",
	"availableAddress": "서울 관악구 봉천동",
	"certificate": "대한애견협회 1급 자격증",
	"score": 9,
	"imagePath": "알이아ㅓ"
}


#

###펫시터 리스트 출력
GET http://localhost:3010/api/pet-sitters
Content-Type: application/json


#

###특정 펫시터 조회
GET http://localhost:3010/api/reservation/2
Content-Type: application/json


# 

###펫시터 예약하기
POST http://localhost:3010/api/reservation/contract/3
Content-Type: application/json
authorization: Bearer {{token}}

{
	"availableDate": ["2023-12-24T00:00:00.000Z", "2023-12-26T00:00:00.000Z"]
}



#
###펫시터 예약 수정하기
PATCH  http://localhost:3010/api/reservation/contract/3
Content-Type: application/json
authorization: Bearer {{token}}

{
	"availableDate": ["2023-12-26T00:00:00.000Z", "2023-12-24T00:00:00.000Z"]
}

# "availableDate": ["2023-12-26T00:00:00.000Z", "2023-12-24T00:00:00.000Z"]


#
###펫시터 예약 삭제하기
DELETE  http://localhost:3010/api/reservation/contract/3
Content-Type: application/json
authorization: Bearer {{token}}




#

###팻시터 리뷰 생성
POST http://localhost:3010/api/pet-sitters/3/review
Content-Type: application/json

{
	"petSitterId": 3,
	"userId":2,
	"title": "좋아요",
	"content": "세심하게 배려해주셧어요",
	"score": 8
}