@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZW1iZXJJZCI6OSwibmFtZSI6IuydkeuUlCIsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsInJvbGUiOiJVc2VyIiwiaWF0IjoxNzAyNzk1NjQ3LCJleHAiOjE3MDI3OTkyNDd9.8MFnRHE-pq6rId19gjEMryN6Rd--wkGJX2dSm7rgcQE

###펫시터 리스트 출력
GET http://localhost:3010/api/pet-sitters
Content-Type: application/json


#

###특정 펫시터 조회
GET http://localhost:3010/api/reservation/3
Content-Type: application/json


# 

###펫시터 예약하기
POST http://localhost:3010/api/reservation/contract/3
Content-Type: application/json
authorization: Bearer {{token}}

{
	"availableDate": ["2023-12-31, 2024-01-01"]
}


#
###펫시터 예약 수정하기
# PATCH  http://localhost:3010/api/reservation/contract/3
# Content-Type: application/json
# authorization: Bearer {{token}}

# {
# 	"availableDate": ["2023-12-26T00:00:00.000Z", "2023-12-24T00:00:00.000Z"]
# }


#
###펫시터 예약 삭제하기
DELETE  http://localhost:3010/api/reservation/contract/3
Content-Type: application/json
authorization: Bearer {{token}}


###펫시터 현재 예약 조회하기
GET  http://localhost:3010/api/reservation/contract/check
Content-Type: application/json
authorization: Bearer {{token}}


#

###팻시터 리뷰 생성
POST http://localhost:3010/api/pet-sitters/reviews?petSitterId=3
Content-Type: application/json
authorization: Bearer {{token}}

{
	"content": "문준식 천재 문준식 천재",
	"score": 5
}



#

###팻시터 리뷰 수정
PATCH  http://localhost:3010/api/pet-sitters/reviews/48
Content-Type: application/json
authorization: Bearer {{token}}

{
	"content": "수정2_세심하게 배려해주셧어요",
	"score": 1
}


#

###팻시터 리뷰 삭제
DELETE http://localhost:3010/api/pet-sitters/reviews/22
Content-Type: application/json
authorization: Bearer {{token}}

#

###팻시터 리뷰 보여주기
GET http://localhost:3010/api/pet-sitters/reviews?petSitterId=1
Content-Type: application/json
# authorization: Bearer {{token}}

